

server:
  port: 8190
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: criticism
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: VIEW-SERVICE
  mvc:
    static-path-pattern: /static/**
#  profiles:
#    active: env

eureka:
  client:
    service-url:
      defaultZone:

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000
