

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
<<<<<<< HEAD
  profiles:
    active: enc

#  datasource:
#    name:
#    url:
#    username:
#    password:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: VIEW-SERVICE
#  mvc:
#    static-path-pattern: /static/**

#eureka:
#  client:
#    service-url:
#      defaultZone:


#fehead:
#  connectionProperties:
#    tokenUrl:
#    backUrl:
=======
  datasource:
    name: criticism
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: VIEW-SERVICE
  mvc:
    static-path-pattern: /static/**
#  profiles:
#    active: env

eureka:
  client:
    service-url:
      defaultZone:
>>>>>>> a1cdebe064b7e1906b419ee98bb60a9f6b83a995

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000
