

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  profiles:
    active: enc

#  datasource:
#    name:
#    url:
#    username:
#    password:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: VIEW-SERVICE
#  mvc:
#    static-path-pattern: /static/**

#eureka:
#  client:
#    service-url:
#      defaultZone:


#fehead:
#  connectionProperties:
#    tokenUrl:
#    backUrl:

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000
