

server:
  port: 8190
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: criticism
    url: jdbc:mysql://111.230.138.67:3306/delivery
    username: root
    password: fehead123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: VIEW-SERVICE
  mvc:
    static-path-pattern: /static/**
#  profiles:
#    active: env

eureka:
  client:
    service-url:
#      defaultZone: http://10.111.229.84:8761/eureka
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000
